name: dan-crm

on:
  push:
    branches: [ master, develop, feature/deploy ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy settings
      run: |
        cp core/local_settings.example.py core/local_settings.py
        cd deploy
        cp .env.example .env
    - name: Pull images
      run: docker-compose pull
    - uses: satackey/action-docker-layer-caching@v0.0.8
      continue-on-error: true
    - name: Build and run containers
      run: docker-compose up --build
    - name: Test with pytest
      run: docker exec deploy_api_1 pytest