name: dan-crm

on:
  push:
    branches: [ master, develop, feature/deploy ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: postgres
    steps:
    - uses: actions/checkout@v2
    - run: |
#        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - run: cp core/local_settings.example.py core/local_settings.py
    - run: pytest